In [50]:
# Import the dependencies.
import pandas as pd
import gmaps
import gmaps.datasets
import requests
import matplotlib


class InvalidPointException(Exception):
    pass

# Import the API key.
from config import g_key

In [51]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/WeatherPy_challenge.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Snow inches (last 3 hours),Rain inches (last 3 hours)
0,0,Tuktoyaktuk,CA,2020-02-23 17:51:36,69.45,-133.04,-7.6,83,90,13.87,light snow,0.00,0.0
1,1,Severo-Kurilsk,RU,2020-02-23 17:55:57,50.68,156.12,23.5,96,100,37.63,snow,3.06,0.0
2,2,Atuona,PF,2020-02-23 17:55:57,-9.80,-139.03,81.3,78,20,15.30,light rain,0.00,0.5
3,3,Hermanus,ZA,2020-02-23 17:55:58,-34.42,19.23,66.0,70,0,5.01,clear sky,0.00,0.0
4,4,Altamira,BR,2020-02-23 17:52:45,-3.20,-52.21,82.4,83,75,8.05,broken clouds,0.00,0.0

In [52]:
# Get the data types
city_data_df.dtypes

City_ID                         int64
City                           object
Country                        object
Date                           object
Lat                           float64
Lng                           float64
Max Temp                      float64
Humidity                        int64
Cloudiness                      int64
Wind Speed                    float64
Current Description            object
Snow inches (last 3 hours)    float64
Rain inches (last 3 hours)    float64
dtype: object

In [53]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [73]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
rain_fall = str(input("Do you want it to be raining? (yes/no)"))
snow_fall =  str(input("Do you want it to be snowing? (yes/no)"))

What is the minimum temperature you would like for your trip? 0
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no)no
Do you want it to be snowing? (yes/no)no

In [74]:
if (rain_fall == "yes"): 
    min_rain_fall = 0.000001
    max_rain_fall = 3000
else:
    min_rain_fall = 0
    max_rain_fall = 0.000001
    
print(min_rain_fall) 
print(max_rain_fall)

0
1e-06

In [75]:
if (snow_fall == "yes"): 
    min_snow_fall = 0.000001
    max_snow_fall = 3000
else:
    min_snow_fall = 0
    max_snow_fall = 0.000001
    
print(min_snow_fall) 
print(max_snow_fall)

0
1e-06

In [76]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) & \
                                       (city_data_df["Rain inches (last 3 hours)"] >= min_rain_fall) & \
                                       (city_data_df["Rain inches (last 3 hours)"] <= max_rain_fall) & \
                                       (city_data_df["Snow inches (last 3 hours)"] >= min_snow_fall) & \
                                       (city_data_df["Snow inches (last 3 hours)"] <= max_snow_fall)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Snow inches (last 3 hours),Rain inches (last 3 hours)
3,3,Hermanus,ZA,2020-02-23 17:55:58,-34.42,19.23,66.00,70,0,5.01,clear sky,0.0,0.0
4,4,Altamira,BR,2020-02-23 17:52:45,-3.20,-52.21,82.40,83,75,8.05,broken clouds,0.0,0.0
5,5,Mataura,NZ,2020-02-23 17:55:58,-46.19,168.86,51.01,91,93,1.99,overcast clouds,0.0,0.0
6,6,Kapaa,US,2020-02-23 17:51:41,22.08,-159.32,66.20,88,1,9.17,clear sky,0.0,0.0
7,7,Bereda,ES,2020-02-23 17:53:46,43.27,-7.54,54.00,81,20,4.70,few clouds,0.0,0.0
8,8,Bon Accord,CA,2020-02-23 17:55:59,53.83,-113.42,28.00,52,1,8.05,clear sky,0.0,0.0
9,9,Hilo,US,2020-02-23 17:51:10,19.73,-155.09,68.00,68,1,6.93,clear sky,0.0,0.0
10,10,Avarua,CK,2020-02-23 17:55:59,-21.21,-159.78,80.60,94,100,6.93,light rain,0.0,0.0
11,11,Avanigadda,IN,2020-02-23 17:56:00,16.02,80.92,75.20,88,78,2.24,mist,0.0,0.0
12,12,Kaitong,CN,2020-02-23 17:56:00,44.81,123.15,21.74,65,0,9.82,clear sky,0.0,0.0

In [77]:
preferred_cities_df.count()

City_ID                       439
City                          439
Country                       437
Date                          439
Lat                           439
Lng                           439
Max Temp                      439
Humidity                      439
Cloudiness                    439
Wind Speed                    439
Current Description           439
Snow inches (last 3 hours)    439
Rain inches (last 3 hours)    439
dtype: int64

In [78]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng", 'Current Description' ]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

          City Country  Max Temp    Lat     Lng Current Description Hotel Name
3     Hermanus      ZA     66.00 -34.42   19.23           clear sky
4     Altamira      BR     82.40  -3.20  -52.21       broken clouds
5      Mataura      NZ     51.01 -46.19  168.86     overcast clouds
6        Kapaa      US     66.20  22.08 -159.32           clear sky
7       Bereda      ES     54.00  43.27   -7.54          few clouds
8   Bon Accord      CA     28.00  53.83 -113.42           clear sky
9         Hilo      US     68.00  19.73 -155.09           clear sky
10      Avarua      CK     80.60 -21.21 -159.78          light rain
11  Avanigadda      IN     75.20  16.02   80.92                mist
12     Kaitong      CN     21.74  44.81  123.15           clear sky

In [79]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,}

In [80]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [84]:
hotel_df.head(100)

# Create the output file (CSV).
output_data_file = "weather_data/WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [85]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [83]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(heat_layer)
fig.add_layer(marker_layer)


# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))